<?php

namespace Sdz\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getByCategory(array $categories_names)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->join('a.categories', 'c')
           ->where($qb->expr()->in('c.name', $categories_names));

        return $qb->getQuery()
                  ->getResult();
    }

    public function getArticles($numberPerPage, $page)
    {
        $query = $this->createQueryBuilder('a')
                      ->leftJoin('a.image', 'i')
                      ->addSelect('c')
                      ->leftJoin('a.comments', 'c')
                      ->addSelect('c')
                      ->orderBy('a.date', 'DESC')
                      ->getQuery();

        $query->setFirstResult(( $page-1) * $numberPerPage)
              ->setMaxResults($numberPerPage);

        return new Paginator($query);
    }
}
