sdzblog_index:
    pattern: /{page}
    defaults: { _controller: SdzBlogBundle:Blog:index, page: 1 }
    requirements:
        page: \d*

sdzblog_see:
    pattern: /article/{id}
    defaults: { _controller: SdzBlogBundle:Blog:see }
    requirements:
        id: \d+

sdzblog_add:
    pattern: /add
    defaults: { _controller: SdzBlogBundle:Blog:add }

sdzblog_modify:
    pattern: /modify/{id}
    defaults: { _controller: SdzBlogBundle:Blog:modify }
    requirements:
        id: \d+

sdzblog_delete:
    pattern: /delete/{id}
    defaults: { _controller: SdzBlogBundle:Blog:delete }
    requirements:
        id: \d+
