parameters:
#    sdz_blog.example.class: Sdz\BlogBundle\Example

services:
    # Convention: applicationName_bundleName.service
    sdz_blog.antispam:
        class: Sdz\BlogBundle\Antispam\SdzAntispam
        arguments: [@mailer, %locale%, 4]
